name: Install and cache
description: Setup the runner environment, by installing dependencies and restoring caches

inputs:
  cache-key:
    description: The key to the cache
    required: true

runs:
  using: composite
  steps:
    - name: Update cache
      id: cache-update
      uses: actions/cache/save@v4
      with:
        path: .nx
        key: ${{ inputs.cache-key }}
