name: "Check and build"
on:
  push:
    branches:
      - release
      - main
      - chore/CRC-28/single-job

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      cache-key: nx-cache
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/run-nx-target
        with:
          target: lint
  check-spell:
    needs: lint
    name: Check spell
    runs-on: ubuntu-latest
    env:
      cache-key: nx-cache
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/run-nx-target
        with:
          target: check:spell
  check-types:
    needs: check-spell
    name: Check types
    runs-on: ubuntu-latest
    env:
      cache-key: nx-cache
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/run-nx-target
        with:
          target: check:types
  test-unit:
    needs: check-types
    name: Test unit
    runs-on: ubuntu-latest
    env:
      cache-key: nx-cache
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/run-nx-target
        with:
          target: test:unit
  build:
    needs: test-unit
    name: Build
    runs-on: ubuntu-latest
    env:
      cache-key: nx-cache
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/run-nx-target
        with:
          target: build
  test-component:
    needs: build
    name: Test component
    runs-on: ubuntu-latest
    env:
      cache-key: nx-cache
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/run-nx-target
        with:
          target: test:component
