name: "Check and build"
on:
  push:
    branches:
      - feat/CRC-28/migration

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/install
        id: install
      # NOTE: Ideally, the cache should be saved again after each job, but it is not working as expected. The error "Unable to reserve cache with key X. Another job may be creating this cache"
      # This produce that the cache is only saved the first time we push to the branch. Every consequent modification produces tasks to be re executed always.
      - name: Nx cache
        uses: actions/cache@v4
        with:
          path: .nx
          key: nx-cache-${{ github.workflow }}-${{ github.ref }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        if: github.event_name == 'pull_request'
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: ${{ github.event.pull_request.base.ref }}
      - name: Lint - Affected
        if: github.event_name == 'pull_request'
        run: NX_REJECT_UNKNOWN_LOCAL_CACHE=0 pnpm nx affected -t lint --base=origin/${{ github.event.pull_request.base.ref }} --head=HEAD
      - name: Lint
        if: github.event_name != 'pull_request'
        run: NX_REJECT_UNKNOWN_LOCAL_CACHE=0 pnpm nx run-many --target=lint --all
      - name: Check spell - Affected
        if: github.event_name == 'pull_request'
        run: NX_REJECT_UNKNOWN_LOCAL_CACHE=0 pnpm nx affected -t check:spell --base=origin/${{ github.event.pull_request.base.ref }} --head=HEAD
      - name: Check spell
        if: github.event_name != 'pull_request'
        run: NX_REJECT_UNKNOWN_LOCAL_CACHE=0 pnpm nx run-many --target=check:spell --all
      - name: Check types
        if: github.event_name != 'pull_request'
        run: NX_REJECT_UNKNOWN_LOCAL_CACHE=0 pnpm nx run-many --target=check:types --all
      - name: Test unit
        if: github.event_name != 'pull_request'
        run: NX_REJECT_UNKNOWN_LOCAL_CACHE=0 pnpm nx run-many --target=test:unit --all
      - name: Build
        if: github.event_name != 'pull_request'
        run: NX_REJECT_UNKNOWN_LOCAL_CACHE=0 pnpm nx run-many --target=build --all
      - name: Test component
        if: github.event_name != 'pull_request'
        run: NX_REJECT_UNKNOWN_LOCAL_CACHE=0 pnpm nx run-many --target=test:component --all
