name: "Check and build"
on:
  push:
    branches:
      - feat/CRC-28/migration

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/install
        id: install
      - name: Lint
        run: pnpm nx run-many --target=lint --all
      - uses: ./.github/actions/update-cache
        with:
          cache-key: ${{ steps.install.outputs.cache-key }}

  check-spell:
    name: Check spelling
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/install
        id: install
      - name: Check spelling
        run: pnpm nx run-many --target=check:spell --all
      - uses: ./.github/actions/update-cache
        with:
          cache-key: ${{ steps.install.outputs.cache-key }}

  check-types:
    name: Check types
    runs-on: ubuntu-latest
    needs: check-spell
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/install
        id: install
      - name: Check types
        run: pnpm nx run-many --target=check:types --all
      - uses: ./.github/actions/update-cache
        with:
          cache-key: ${{ steps.install.outputs.cache-key }}
