name: "Check and build"
on:
  push:
    branches:
      - feat/CRC-28/migration

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/install
        id: install
      - name: Nx cache
        id: cache-nx
        uses: actions/cache@v4
        with:
          path: .nx
          key: nx-cache-lint-${{ github.ref }}
      - name: Lint
        run: pnpm nx run-many --target=lint --all

  check-spell:
    name: Check spelling
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/install
        id: install
      - name: Nx cache
        id: cache-nx
        uses: actions/cache@v4
        with:
          path: .nx
          key: nx-cache-check-spell-${{ github.ref }}
          restore-keys: |
            nx-cache-lint-${{ github.ref }}
      - name: Check spelling
        run: pnpm nx run-many --target=check:spell --all

  check-types:
    name: Check types
    runs-on: ubuntu-latest
    needs: check-spell
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: ./.github/actions/install
        id: install
      - name: Nx cache
        id: cache-nx
        uses: actions/cache@v4
        with:
          path: .nx
          key: nx-cache-check-types-${{ github.ref }}
          restore-keys: |
            nx-cache-check-spell-${{ github.ref }}
      - name: Check types
        run: pnpm nx run-many --target=check:types --all
      - name: Update cache
        id: cache-update
        uses: actions/cache/save@v4
        with:
          path: ./.nx
          key: ${{ steps.cache-nx-restore.outputs.cache-primary-key }}
